### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by konfusator** [torrentkino/dnsblock#1]
While logging every DNS request can be useful for debugging it has a serious privacy implication. It would be nice if logging could be configured via `.dnsblock` by a special comment like

`#%LOG:(ALL|BLOCK|NONE)`

with the obvious semantics.

**Comment by torrentkino** [comment]
Hey konfusator,

dnsblock does not log those requests anymore by default. I created a new module dnsblock_debug for that purpose. Please install the new release to activate this feature.

Thank you for using dnsblock. :)

Aiko
